FROM golang:1.17

RUN apt update

RUN apt -y upgrade

RUN apt -y install mc

ADD . /go/src/test1

WORKDIR /go/src/test1

RUN go install /go/src/test1/server

EXPOSE 5555

EXPOSE 8090

ENTRYPOINT ["/go/bin/server"]

